### ISSUE TITLE
Getting: Error: Unable to load shared library /opt/node/lib/node_modules/kstat/build/Release/kstat.node

### ISSUE THREAD

**Issue by szaydel** [joyent/node-kstat#4]
I just tried to build node and installed the kstat module, but seems I keep getting this error. I am getting the following, and have been unable to figure out why.

``` module.js:477
  process.dlopen(filename, module.exports);
          ^
Error: Unable to load shared library /opt/node/lib/node_modules/kstat/build/Release/kstat.node
    at Object..node (module.js:477:11)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/opt/node/lib/node_modules/kstat/examples/kstat.js:9:13)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
```

**Comment by bcantrill** [comment]
This is an ancient issue that I can't currently reproduce; closing it out.
